<a href="https://colab.research.google.com/github/williambrunos/Deep-Learning-Neuro-evolution/blob/main/First_Implementations/first_implementations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# First Implementations with tensorflow

## Abstract

This notebook tries to implement some neural netowork used to solve some problem and tries to evolve the weights of it using neural evolution, implemented with [tensorflow](https://www.tensorflow.org/probability/api_docs/python/tfp/optimizer/differential_evolution_minimize)

````Python
tfp.optimizer.differential_evolution_minimize(
    objective_function,
    initial_population=None,
    initial_position=None,
    population_size=50,
    population_stddev=1.0,
    max_iterations=100,
    func_tolerance=0,
    position_tolerance=1e-08,
    differential_weight=0.5,
    crossover_prob=0.9,
    seed=None,
    name=None
)
````

**obs**: if you read the documentation of this function, you'll see that the evolutionary algorithm will try to minimize the objective function, rather than maximize it. Because of this, it's important to implement a objective function with the negative value of the mathmatical expression.

"A candidate s_1 is considered better than s_2 if f(s_1) < f(s_2)." - The function documentation

In [8]:
import tensorflow as tf
import tensorflow_probability as tfp
import time

import pandas as pd
import numpy as np

In [9]:
population_size = 40
# With an initial population and a multi-part state.
initial_population = (tf.random.normal([population_size]),
                        tf.random.normal([population_size]))

print(f'initial pop: {initial_population}') 

def easom_fn(x, y):
  return -(tf.math.cos(x) * tf.math.cos(y) *
             tf.math.exp(-(x-np.pi)**2 - (y-np.pi)**2))

st = time.time()

optim_results = tfp.optimizer.differential_evolution_minimize(
    easom_fn,
    initial_population=initial_population,
    max_iterations=50,
    seed=43210)

et = time.time()

time_spent = et - st 
print(f'time spent {time_spent}')

print(optim_results.converged)
print(optim_results.position)  # Should be (close to) [pi, pi].
print(optim_results.objective_value)    # Should be -1.
print(optim_results.final_population) # final population
print(optim_results.objective_value) # final value of objective fun. on the final position
print(optim_results.final_objective_values)

# With a single starting point
initial_position = (tf.constant(1.0), tf.constant(1.0))

optim_results = tfp.optimizer.differential_evolution_minimize(
                easom_fn,
                initial_position=initial_position,
                population_size=40,
                population_stddev=2.0,
                seed=43210)

initial pop: (<tf.Tensor: shape=(40,), dtype=float32, numpy=
array([-1.1506878 ,  0.6311716 , -0.34235987,  1.2067575 , -0.23521943,
       -1.1832876 , -0.04409842, -0.5915712 , -0.8513796 ,  0.93963796,
       -0.3926571 ,  0.8257857 ,  0.74832577,  1.3140789 ,  1.1822169 ,
        0.90320224,  0.70792824,  0.9428253 ,  0.7002732 , -2.0490952 ,
        0.60346264, -0.05436082, -0.03358738,  0.57044846,  0.16950017,
       -0.20063397, -0.1691871 , -0.8320669 , -1.4917945 ,  0.02345422,
       -1.5815673 ,  0.37632462, -0.68456924,  0.12658094, -0.39613244,
        0.1307614 ,  0.59872085,  2.0896833 , -0.27177754, -0.14830233],
      dtype=float32)>, <tf.Tensor: shape=(40,), dtype=float32, numpy=
array([ 0.54629076,  0.19631886,  0.90113014,  0.9917434 , -0.64886135,
       -0.14166357, -0.958315  , -1.305818  , -0.48991486,  0.36281788,
        0.49761158, -0.6057028 ,  0.5543006 ,  0.24301495,  0.13177307,
        0.7371027 ,  1.5186855 , -0.7243141 ,  0.41669425,  1.0677704 ,
    

In [4]:
np.array(optim_results.position)

array([3.141433, 3.141627], dtype=float32)